### PR TITLE
Add Storybook, #11

### PR DESCRIPTION
**Pull request by exiam**
I have installed Storybook on your project.
Don't know if this is the best way but looks good. :smile: 

Also, I have taken the liberty to move your config view as a standalone component for better reusability (under 'pages/components/config'). There you will find the component view and the stories.

To run Storybook : `yarn run storybook`

I used the following resources :
- https://storybook.js.org/docs/guides/guide-react/
- https://www.manuel-schoebel.com/blog/nextjs-typescript-storybook-setup
- https://github.com/mrisoli/nextjs-boilerplate

I'm waiting for your feedbacks.

### CODE REVIEW

**Comment by hugo-s29** [comment]
HI,

Thanks for taking a look. 

However, it will be even better if the __components__ and the __types__ weren't in the `pages` folder: **NextJS serve everything inside the `pages` folder**.

Except this little change to do, **it works so it's good**.

Bye,
Hugo

**Comment by exiam** [comment]
Hi,

Yes, exaclty, I missed that point! 
I will fix this.

Thanks.

**Comment by exiam** [comment]
I moved the `components` folder and type declarations outside the `pages` folder (for the type declarations, I moved it to `@types` folder).

Also I have rebased my branch on master to prevent merge conflicts.

**Comment by hugo-s29** [comment]
#### 📝Changed routes:


| [**/**](https://theprojectalpha-git-fork-exiam-feat11addstorybook.hugos29.now.sh/) |
|:-:|
|<a href="https://theprojectalpha-git-fork-exiam-feat11addstorybook.hugos29.now.sh/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=microlink-screenshot.nyc3.digitaloceanspaces.com/pyMralc4rUYG2kLCPqSDw6nAN3E_">(view full size)</a> |







Commit 06b6bf5b1c51a7f48d3021eefd0341aeb47d76a2 (https://theprojectalpha-git-fork-exiam-feat11addstorybook.hugos29.now.sh).

**Comment by hugo-s29** [comment]
Thanks for the contribution @exiam

**Comment by hugo-s29** [comment]
@all-contributors please add @exiam for code and platform

**Comment by hugo-s29** [comment]
Hi @exiam,

I've made **another issue** related to `Storybook`: #31 .

Could you take a look ?

Bye,
Hugo

**Pull request merged**
