### PR TITLE
Add Storyshots, #31

### PR DESCRIPTION
**Pull request by exiam**
Hi, 

I added storyshots on project. 
I tried a lot of configuration changes before successfully running storyshots.

The file initializing storyshots : `components/storyshots.test.ts` (maybe not the ideal location, let me know)

Some resources:
- https://github.com/storybookjs/storybook/tree/master/addons/storyshots/storyshots-core
- https://kulshekhar.github.io/ts-jest/user/config/
- https://github.com/elastic/eui/issues/2242

I'm waiting for your review. :smiley:

### CODE REVIEW

**Comment by hugo-s29** [comment]
Hi @exiam,

#### Thanks for your contribution ! 🎉

Can you just see if you can install `storybook-addon-specifications` since you know a lot with **Storybook** ?

Huge thanks,
Hugo

**Comment by hugo-s29** [comment]
@all-contributors please add @exiam for code, test and tool

**Comment by hugo-s29** [comment]
And sorry about that but I added **some components** and **committed them** which **created merge conflicts**...  🙄

**Comment by exiam** [comment]
Hi!

I finally find the time and a way to implements `storybook-addon-specifications`.

As we are using the Component Story Format (CSF) for writing stories, it's more complex to configure correctly this addon. Actually, you can write tests inside stories and run them in Storybook interface but you can't run this tests with `yarn test` (got some conflicts with storyshots addon). I'll let you know if I find a solution for that.

I let you review the updated code. :smiley:

**Comment by hugo-s29** [comment]
Thanks for your contribution 🎉

**Comment by hugo-s29** [comment]
@all-contributors please add @exiam  for tests, code and tool

**Pull request merged**
